### ISSUE TITLE
uint64_t  array problem

### ISSUE THREAD

**Issue by MouseChannel** [MircoWerner/VkRadixSort#4]
can I just change 
`
#define BITS 32 // sorting uint32_t
#define ITERATIONS 4 
`
to
`
#define BITS 64 // sorting uint64_t
#define ITERATIONS 8 
`
but it did not work.

**Comment by MircoWerner** [comment]
Hi, the naming and the comment for the macro `BITS` were misleading/wrong. It must always be set to 32 regardless of whether uint32_t or uint64_t is sorted. I've removed the macro in the newest version on the main branch. With the newest version, you have to change the following for uint64_t : ff1359bec0e4dd7812c52556ff3d6b7ac371e120 (latest commit on example-uint64 branch)
Hope this helps and works for you!

**Comment by MouseChannel** [comment]
```
[SingleRadixSort] Sorting 1000000 64bit numbers.
[SingleRadixSort] GPU sort finished in 30.729[ms].
[SingleRadixSort] CPU sort finished in 250.25[ms].
[SingleRadixSort] 1864908 = reference[0] != outBuffer[0] = 0
TEST FAILED.
```
im using the new uint64_t code, what  I did wrong?....
Im just `#define SORT_64_BIT` in header file

**Comment by MouseChannel** [comment]
works, thank you very much!!!
